# Generated by Django 5.0.8 on 2024-08-18 09:24

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
        ('wagtaildocs', '0013_delete_uploadeddocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='NavigationSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=20, verbose_name='First name')),
                ('last_name', models.CharField(blank=True, max_length=20, verbose_name='Last name')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='LinkedIn URL')),
                ('github_url', models.URLField(blank=True, verbose_name='GitHub URL')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-Mail_Adress')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('landing_section', 3), ('introduction_section', 7), ('project', 10), ('motivation', 14), ('skill_set', 16)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'default': 'title', 'help_text': 'first attention for visitors', 'max_length': 50, 'verbose_name': 'attention_title'}), 1: ('wagtail.blocks.CharBlock', (), {'default': 'write something great', 'help_text': 'catch your visitors', 'max_length': 200, 'verbose_name': 'catcher'}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Background image for the landing page', 'required': False}), 3: ('wagtail.blocks.StructBlock', [[('attention_title', 0), ('catcher', 1), ('background_image_landing', 2)]], {}), 4: ('wagtail.blocks.CharBlock', (), {'max_length': 50, 'required': False}), 5: ('wagtail.blocks.TextBlock', (), {}), 6: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 7: ('wagtail.blocks.StructBlock', [[('greeting', 4), ('introduction_text', 5), ('personal_image', 6)]], {}), 8: ('wagtail.snippets.blocks.SnippetChooserBlock', ('streams.Project',), {}), 9: ('wagtail.blocks.StreamBlock', [[('project', 8)]], {'blank': True, 'null': True}), 10: ('wagtail.blocks.StructBlock', [[('projects', 9)]], {}), 11: ('wagtail.snippets.blocks.SnippetChooserBlock', ('streams.Quote',), {}), 12: ('wagtail.blocks.StreamBlock', [[('quote', 11)]], {}), 13: ('wagtail.blocks.TextBlock', (), {'max_length': 200, 'required': False}), 14: ('wagtail.blocks.StructBlock', [[('quotes', 12), ('final_words', 13)]], {}), 15: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('hard', 'Hard Skill'), ('soft', 'Soft Skill')], 'help_text': 'Choose whether to display Hard or Soft Skills'}), 16: ('wagtail.blocks.StructBlock', [[('header', 4), ('skill_type', 15)]], {})}, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='cv',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.document', verbose_name='CV'),
        ),
    ]
