# Generated by Django 4.2.2 on 2024-08-04 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
        ('wagtaildocs', '0012_uploadeddocument'),
        ('home', '0002_homepage_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='content',
        ),
        migrations.AddField(
            model_name='homepage',
            name='catcher',
            field=models.CharField(default='write something greate', help_text='catch your visitors', max_length=200, verbose_name='catcher'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='cv',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.document', verbose_name='CV'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='landing_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='background_image_landing'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='landing_title',
            field=models.CharField(default='title', help_text='first attention for visitors', max_length=50, verbose_name='attention_title'),
        ),
    ]
