# Generated by Django 5.0.8 on 2024-08-14 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_alter_homepage_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='NavigationSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=20, verbose_name='First name')),
                ('last_name', models.CharField(blank=True, max_length=20, verbose_name='Last name')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='LinkedIn URL')),
                ('github_url', models.URLField(blank=True, verbose_name='GitHub URL')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-Mail_Adress')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
