# Generated by Django 5.0.8 on 2024-10-18 08:49

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('richtextpage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='richtextpage',
            name='body',
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
    ]
