# Generated by Django 4.2.2 on 2024-08-04 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='skill_type',
            field=models.CharField(choices=[('hard', 'Hard Skill'), ('soft', 'Soft Skill')], default='hard', help_text='Select whether this is a Hard Skill or Soft Skill', max_length=4),
        ),
    ]
