# Generated by Django 5.0.8 on 2024-08-18 09:24

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0001_initial'),
        ('wagtailimages', '0026_delete_uploadedimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='skill_type',
            field=models.CharField(choices=[('hard', 'Hard Skill'), ('soft', 'Soft Skill')], default='hard', help_text='Select whether this is a Hard Skill or Soft Skill', max_length=4),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('links', wagtail.fields.StreamField([('link', 0)], blank=True, block_lookup={0: ('wagtail.blocks.URLBlock', (), {'required': True})}, null=True)),
                ('skillset', wagtail.fields.StreamField([('skill', 0)], blank=True, block_lookup={0: ('wagtail.snippets.blocks.SnippetChooserBlock', ('streams.Skill',), {})}, null=True)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
            },
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote_text', models.TextField(help_text='Enter the text of the quote here.', verbose_name='Quote')),
                ('author', models.CharField(blank=True, help_text='Name of the person who said or wrote the quote.', max_length=255, null=True, verbose_name='Author')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name="Author's Image")),
            ],
            options={
                'verbose_name': 'Quote',
                'verbose_name_plural': 'Quotes',
            },
        ),
    ]
