# Generated by Django 5.0.8 on 2024-08-19 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0002_skill_skill_type_project_quote'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='description_mobil',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, max_length=700, null=True),
        ),
    ]
