# Generated by Django 5.0.8 on 2024-08-19 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0003_project_description_mobil_alter_project_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
