# Generated by Django 5.0.8 on 2024-08-14 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0004_quotesnippet'),
        ('wagtailimages', '0026_delete_uploadedimage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QuoteSnippet',
            new_name='Quote',
        ),
    ]
