# Generated by Django 5.0.8 on 2024-08-29 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0005_alter_project_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='quote_text',
            field=models.TextField(help_text='Enter the text of the quote here.', max_length=100, verbose_name='Quote'),
        ),
    ]
