# Generated by Django 5.0.8 on 2024-09-16 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0006_alter_quote_quote_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='quote_text',
            field=models.TextField(help_text='Enter the text of the quote here.', max_length=200, verbose_name='Quote'),
        ),
    ]
