# Generated by Django 5.0.8 on 2024-10-13 18:08

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0008_skill_star_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='description_mobil',
        ),
        migrations.RemoveField(
            model_name='project',
            name='image',
        ),
        migrations.AddField(
            model_name='project',
            name='images',
            field=wagtail.fields.StreamField([('image_list', 1)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 1: ('wagtail.blocks.ListBlock', (0,), {'label': 'Bilder'})}),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
