# Generated by Django 5.0.8 on 2024-10-13 18:26

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0009_remove_project_description_mobil_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='images',
            field=wagtail.fields.StreamField([('image', 0)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Bild'})}),
        ),
    ]
