# Generated by Django 5.0.8 on 2024-10-13 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0011_alter_project_links'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
